config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
resources :users
resources :books,only:[:index,:show,:edit,:update,:create,:destroy]
root to: "homes#top"
get "home/about"=> "homes#about"
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
 has_one_attached :image
 belongs_to :user
 validates :title,presence:true
 validates :body,presence:true, length:{maximum: 200}
 
  
end  

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_one_attached :profile_image
  validates :name, presence: true, uniqueness: { case_sensitive: false } ,length: { minimum: 2, maximum: 20}
  validates :introduction, length: {maximum: 50}
  
  def get_profile_image(size)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image-1.jpg')
      profile_image.attach(io: File.open(file_path),filename: 'default-image.jpg',content_type:'image/jpeg')
    end 
    profile_image.variant(resize:size).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

before_action :authenticate_user!, except:[:top,:about]    
before_action :configure_permitted_parameters, if: :devise_controller?


def after_sign_in_path_for(resource)
  user_path(current_user)
end

def after_sign_out_path_for(resource)
  root_path
end

protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
 end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
 def create
    @book= Book.new(book_params)
    @book.user_id= current_user.id
     if @book.save
     flash[:notice]= 'You have created book successfully'
     redirect_to book_path(@book.id)
     else
     @books= Book.all
     @user= current_user
     render :index
     end
 end  

  def index
    @books= Book.all
    @book=Book.new
    @user= current_user
  end

  def show
    @book= Book.find(params[:id])
    @user= @book.user
    @new_book= Book.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end
  
  def update
     @book= Book.find(params[:id])
     if @book.update(book_params)
         flash[:notice]= 'You have update book successfully'
         redirect_to book_path(@book.id)
     else
        render :edit
     end
  end
  
  def destroy
       book= Book.find(params[:id])
       book.destroy
       flash[:notice]= 'You have destroyed book successfully'
       redirect_to books_path
  end 
 
 private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  

  def index
    @users =User.all
    @user =current_user
    @book =Book.new
  end
  
  def show
    @user= User.find(params[:id])
    @books= @user.books
    @book= Book.new
  end

  def edit
    @user= User.find(params[:id])
    if @user == current_user
    else
     redirect_to user_path(current_user)
    end
  end  
  
  def update
    @user= User.find(params[:id])
    if @user.update(user_params)
     flash[:notice]= 'You have updated user successfully'
     redirect_to user_path(@user.id)
    else
      render:edit
    end
  end

  private
  
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
            <% if @book.errors.any? %>
      <div class ="error">
        <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
      <% end %>
      
      <%= form_with model: @book do |f| %>
        <div class="user-name my-2">Title</div>
          <%= f.text_field :title ,class: "form-control" %>

        <div class="form-body my-2">Opinion</div>
          <%= f.text_area :body , class: "form-control mb-3" %>

        <div class="upload mb-2">
          <button type="submit" class="btn btn-success">Update Book</button>
        </div>
      <% end %>
      <%= link_to "Show",book_path(@book.id) %>
      |
      <%= link_to "Back",books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
    </ul>
   <% end %>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= image_tag @user.get_profile_image ("100x100") %>
      <table class="table">
        <tbody>
         <tr>
          <th>name</th>
          <th><%= @user.name %></th>
         </tr>
         <tr>
          <th>introduction</th>
          <th><%= @user.introduction %></th>
         </tr>
        </tbody> 
      </table>
      <div class="row">
         <%= link_to edit_user_path(@user.id), class: 'btn btn-outline-secondary btn-block' do %>
         <i class="fas fa-user-cog"></i>
        <% end %>
      </div>


      <h2 class="mt-3">New book</h2>
      <%= form_with model:@book, local:true do |f| %>
         <div class="form-group">
            <label for="book_title">Title</label>
            <%= f.text_field :title %>
         </div>
         <div class="form-group">
            <label for="form_opinion">Opinion</label>
            <%=f.text_area :body %>
         </div>
         <div class="form-group">
             <%=f.submit 'Create Book',class:"btn btn-success" %>
         </div>
      <% end %> 
     </div>
     
     <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
         <tr>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
         </tr>
        </thead>
          <tbody>
            <% @books.each do |book| %>
            <tr>
             <td>
               <%= link_to user_path(book.user) do %>
                 <%= image_tag book.user.get_profile_image("50x50") %>
                <% end %>
             </td>   
             <td><%= link_to book.title,book_path(book.id)%></td>
             <td><%= book.body %></td>
            </tr>
            <% end %>
          </tbody>  
        </table>
      </div>
    </div>
  </div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= image_tag @user.get_profile_image ("70x70") %>
      <table class="table">
        <tbody>
         <tr>
           <th>name</th>
           <th><%= @user.name %></th>
         </tr>
         <tr>
           <th>introduction</th>
           <th><%= @user.introduction %></th>
         </tr>
        </tbody>
      </table>
      <div class="row">
        <%= link_to edit_user_path(@user.id), class:'btn btn-outline-secondary btn-block' do %>
           <i class="fas fa-user-cog"></i>
        <% end %>
      </div>
      
      <h2 class="mt-3">New book</h2>
      <%= form_with model: @new_book, local:true do |f| %>
         <div class="form-group">
           <label for="book_title">Title</label>
           <%= f.text_field :title %>
          </div>
          <div class="form-group">
           <label for="form_opinion">Opinion</label>
            <%= f.text_area :body %>
          </div>
          <div class="form-group">
            <%= f.submit 'Create Book', class:"btn btn-success" %>
          </div>
      <% end %>
    </div>
      
            
      <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>
        <table class="table">
          <tbody>
            <tr>
              <td><%= image_tag @user.get_profile_image ("50x50") %></td>
              <td><%= link_to @user.name, user_path(@user.id) %></td>
              <td><%= link_to @book.title, book_path(@book.id) %></td>
              <td><%= @book.body %></td>
              <% if @user.id == current_user.id %>
              <td>
                <%=link_to "Edit", edit_book_path(@book.id),class:"btn btn-success" %>
              </td>
              <td>
                <%= link_to "Destroy", book_path(@book.id) , method: :delete,  data: {confirm: "本当に削除しますか？"}, class:"btn btn-danger" %>
              </td>
              <% end %>
             </tr>
          </tbody>
        </table>
      </div>
     </div>
    </div>
  
            

app/views/homes/about.html.erb
<div class="container">
<div class="row">
  <div class="px-3 mx-auto">
    <h1>welcome to <i class="fas fa-book"></i><strong>Bookers<strong> !</h1>
  </div>
</div>
</div>

app/views/homes/top.html.erb
<div class="container">
 <div class="row">
  <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">

<h1>
   welcome to <i class="fas fa-book"></i><strong>Bookers<strong> !!</h1>
 
   <p>In <i class="fas fa-book"></i><strong>bookers</strong></i><br>
      you can share and exchange your opinions, inpressions,and emotions<br>
      about various books!<br><p>
   <div class="btn-wrapper col-10mx-auto"></div>
     <div class="row">
       <%= link_to 'Log in',new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
     </div>
     <div class="row">
       <%= link_to 'Sign up',new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
     </div>
  </div>
 </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
     <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
      <%= link_to root_path, class: 'nav-link text-light' do %> 
       Bookers
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
       <ul class="navbar-nav ml-auto">
      
      <% if user_signed_in? %>
      
       <li class="nav-item">
        <%= link_to user_path(current_user.id), class:'nav-link text-light' do %>
         <i class="fas fa-home"></i>Home
        <% end %>
       </li>
       
       <li class="nav-item">
        <%=link_to users_path, class: 'nav-link text-light' do %>
         <i class="fas fa-users"></i>Users
        <% end %>
       </li>
       
       <li class="nav-item">
        <%= link_to books_path, class:'nav-link text-light' do %>
         <i class="fas fa-book-open"></i>Books
        <% end %>
       </li>
       
       <li>
        <%= link_to destroy_user_session_path, method: :delete,class:'nav-link text-light' do %>
         <i class="fas fa-sign-out-alt"></i> Log out
        <% end %> 
       </li>
     
     <% else %>
      
       <li class="nav-item">
        <%= link_to root_path, class:'nav-link text-light' do %>
         <i class="fas fa-home"></i>Home
        <% end %>
       </li>
       
       <li class="nav-item">
        <%= link_to home_about_path,class:'nav-link text-light' do %>
         <i class="fas fa-link"></i>About    
        <% end %>
       </li>
       
       <li class="nav-item">
        <%= link_to new_user_registration_path, class:'nav-link text-light' do %>
         <i class="fas fa-user-plus"></i>Sign up
        <% end %>
       </li>
       
       <li class="nav-item">
        <%= link_to new_user_session_path, class:'nav-link text-light' do %>
         <i class="fas fa-sign-in-alt"></i>Log in
        <% end %>
       </li>
      <% end %> 
      </ul>
     </div>
    </div>
    </div>
   </header>
   <main>
        <p class="text-success"><%= flash[:notice] %></p>
        <p class="text-danger"><%= flash[:alert] %></p>
    <%= yield %>
   </main>
  </body>
  
  <footer>
    <div class="container mt-5">
      <div class="row">
         <div class="mx-auto">
            <p>CopyRight Infratop.Inc</p>
         </div>
      </div>
    </div>
  </footer>  
</html>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
     <li><%= message %></li>
    <% end %>
  </ul>
 <% end %>


<% if @user.errors.any? %>
  <%= @user.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<h1>user info</h1>

<%= form_with model: @user, local:true do |f| %>

<h4>Image</h4>
<%= f.file_field :profile_image, accept: "image/*" %>

<h4>Name</h4>
<%= f.text_field :name %>

<h4>Introduction</h4>
<%= f.text_area :introduction %>

 <div class="upload mb-2">
   <button type="submit" class="btn btn-secondary">Update User</button>
 </div>

<% end %>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= image_tag @user.get_profile_image ("100x100") %>
      <table class="table">
        <tbody>
         <tr>
          <th>name</th>
          <th><%= @user.name %></th>
         </tr>
         <tr>
          <th>introduction</th>
          <th><%= @user.introduction %></th>
         </tr>
        </tbody> 
      </table>
      <div class="row">
         <%= link_to edit_user_path(@user.id), class: 'btn btn-outline-secondary btn-block' do %>
         <i class="fas fa-user-cog"></i>
        <% end %>
      </div>
      
       <h2 class="mt-3">New book</h2>
      <%= form_with model:@book, local:true do |f| %>
         <div class="form-group">
            <label for="book_title">Title</label>
            <%= f.text_field :title %>
         </div>
         <div class="form-group">
            <label for="form_opinion">Opinion</label>
            <%=f.text_area :body %>
         </div>
         <div class="form-group">
             <%= f.submit 'Create Book',class:"btn btn-success" %>
         </div>
      <% end %> 
     </div>
     
     <div class="col-md-8 offset-md-1">
        <h2>Users</h2>
        <table class="table">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
             <% @users.each do |user| %>
             <tr>
               <td><%= image_tag user.get_profile_image ("50x50") %></td>
               <td><%= user.name %></td>
               <td><%= link_to "Show", user_path(user.id) %></td>
             </tr>
             <% end %>
            </tbody>
           </table>
          </div>
         </div>
        </div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= image_tag @user.get_profile_image ("100x100") %>
      <table class="table">
        <tbody>
         <tr>
          <th>name</th>
          <th><%= @user.name %></th>
         </tr>
         <tr>
          <th>introduction</th>
          <th><%= @user.introduction %></th>
         </tr>
        </tbody> 
      </table>
      <div class="row">
         <%= link_to edit_user_path(@user.id), class: 'btn btn-outline-secondary btn-block' do %>
         <i class="fas fa-user-cog"></i>
        <% end %>
      </div>


      <h2 class="mt-3">New book</h2>
      <%= form_with model:@book, local:true do |f| %>
         <div class="form-group">
            <label for="book_title">Title</label>
            <%= f.text_field :title %>
         </div>
         <div class="form-group">
            <label for="form_opinion">Opinion</label>
            <%=f.text_area :body %>
         </div>
         <div class="form-group">
             <%= f.submit 'Create Book',class:"btn btn-success" %>
         </div>
      <% end %> 
     </div>
     
     <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
         <tr>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
         </tr>
        </thead>
          <tbody>
            <% @books.each do |book| %>
            <tr>
             <td>
               <%= link_to user_path(book.user) do %>
                 <%= image_tag book.user.get_profile_image("50x50") %>
                <% end %>
             </td>   
             <td><%= link_to book.title,book_path(book.id)%></td>
             <td><%= book.body %></td>
            </tr>
            <% end %>
          </tbody>  
        </table>
      </div>
    </div>
  </div>